Contains measure definitions and multiple DAX queries to break down Total Passenger by date, route, driver, and combinations.
Usage:
For ad-hoc queries: open this file in DAX Studio (connect to your Power BI/SSAS model) and run the selected EVALUATE query.
For persistent model measures: copy the MEASURE expressions into Power BI Desktop (Modeling → New measure).
Replace column/table names if your model uses different names (e.g., Date table name or column names). */
/* Measures */ DEFINE MEASURE 'Actual Trips'[Total Passenger] = SUM('Actual Trips'[Passengers On]) MEASURE 'Actual Trips'[Total Passenger All] = CALCULATE
S
U
M
(
′
A
c
t
u
a
l
T
r
i
p
s
′
[
P
a
s
s
e
n
g
e
r
s
O
n
]
)
,
A
L
L
(
′
A
c
t
u
a
l
T
r
i
p
s
′
)
 MEASURE 'Actual Trips'[Avg Passengers Per Trip] = DIVIDE
[
T
o
t
a
l
P
a
s
s
e
n
g
e
r
]
,
C
O
U
N
T
R
O
W
S
(
′
A
c
t
u
a
l
T
r
i
p
s
′
)
 MEASURE 'Actual Trips'[Percent of Total Passenger] = DIVIDE
[
T
o
t
a
l
P
a
s
s
e
n
g
e
r
]
,
[
T
o
t
a
l
P
a
s
s
e
n
g
e
r
A
l
l
]
,
0

/* ------------------------------------------------------------------------

Breakdown by Trip Date (daily) Run this to get day-level totals, trips count, avg per trip and percent of total ------------------------------------------------------------------------ */ EVALUATE SUMMARIZECOLUMNS( 'Actual Trips'[Trip Date], "Total Passenger", [Total Passenger], "Trips", COUNTROWS('Actual Trips'), "Avg Per Trip", [Avg Passengers Per Trip], "Percent of Total", [Percent of Total Passenger] ) ORDER BY 'Actual Trips'[Trip Date]
/* ------------------------------------------------------------------------ 2) Breakdown by Route ------------------------------------------------------------------------ */ EVALUATE SUMMARIZECOLUMNS( 'Actual Trips'[Route], "Total Passenger", [Total Passenger], "Trips", COUNTROWS('Actual Trips'), "Avg Per Trip", [Avg Passengers Per Trip], "Percent of Total", [Percent of Total Passenger] ) ORDER BY [Total Passenger] DESC

/* ------------------------------------------------------------------------ 3) Breakdown by Driver ------------------------------------------------------------------------ */ EVALUATE SUMMARIZECOLUMNS( 'Actual Trips'[Driver], "Total Passenger", [Total Passenger], "Trips", COUNTROWS('Actual Trips'), "Avg Per Trip", [Avg Passengers Per Trip], "Percent of Total", [Percent of Total Passenger] ) ORDER BY [Total Passenger] DESC

/* ------------------------------------------------------------------------ 4) Combined breakdown: Date x Route x Driver (useful for drill-down exports; filter or page if large) ------------------------------------------------------------------------ */ EVALUATE SUMMARIZECOLUMNS( 'Actual Trips'[Trip Date], 'Actual Trips'[Route], 'Actual Trips'[Driver], "Total Passenger", [Total Passenger], "Trips", COUNTROWS('Actual Trips'), "Avg Per Trip", [Avg Passengers Per Trip] ) ORDER BY 'Actual Trips'[Trip Date], [Total Passenger] DESC

/* ------------------------------------------------------------------------ 5) Top N Drivers by Total Passenger (Top 10) ------------------------------------------------------------------------ */ EVALUATE TOPN( 10, ADDCOLUMNS( VALUES('Actual Trips'[Driver]), "TotalPassenger", CALCULATE
S
U
M
(
′
A
c
t
u
a
l
T
r
i
p
s
′
[
P
a
s
s
e
n
g
e
r
s
O
n
]
)
, "Trips", CALCULATE
C
O
U
N
T
R
O
W
S
(
′
A
c
t
u
a
l
T
r
i
p
s
′
)
 ), [TotalPassenger], DESC )

/* ------------------------------------------------------------------------ 6) Monthly totals (requires a Date dimension table: 'Date') Replace 'Date' table/columns if different in your model ------------------------------------------------------------------------ */ EVALUATE SUMMARIZECOLUMNS( 'Date'[Year], 'Date'[MonthNumber], 'Date'[MonthName], "Total Passenger", [Total Passenger], "Trips", COUNTROWS('Actual Trips') ) ORDER BY 'Date'[Year], 'Date'[MonthNumber]

/* ------------------------------------------------------------------------ 7) Absolute total (ignores model filters) ------------------------------------------------------------------------ */ EVALUATE ROW("Total Passenger (All)", [Total Passenger All])

Code
